# list of dependencies for a cucumber-nagios project

#gem "bundler", "0.6.0"
gem "cucumber", "0.6.1"
gem "rspec", "1.3.0"
gem "webrat", "0.6.0"
gem "mechanize", "0.9.3"
gem "templater", "1.0.0"
gem "net-ssh", "2.0.18"

