# list of dependencies for a cucumber-nagios project

#gem "bundler", "0.6.0"
gem "cucumber", "0.4.0"
gem "rspec", "1.2.9"
gem "webrat", "0.5.3"
gem "mechanize", "0.9.3"
gem "templater", "0.5.0"
gem "net-ssh", "2.0.15"

