source :rubygems

gem "cucumber-nagios"
gem "cucumber", "0.10.0"
gem "rspec", "2.3.0"
gem "webrat", "0.7.2"
gem "mechanize", "1.0.0"
gem "templater", "1.0.0"
gem "net-ssh", "2.0.18"
gem "amqp", "0.6.7"



